# Generated by Django 2.2.4 on 2020-06-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=150)),
                ('nombre_propietario', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('cantidad', models.IntegerField()),
                ('direccion', models.CharField(max_length=250)),
                ('departamento', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=250)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('tipo_mascarilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Mascarilla')),
            ],
        ),
    ]
