# Generated by Django 2.2.4 on 2020-06-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imei',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
