# Generated by Django 2.2.4 on 2020-06-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedido_imei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
    ]
